// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: Monitoring.proto

package monitoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RequestDate   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=request_date,json=requestDate,proto3" json:"request_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_Monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_Monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_Monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Client) GetRequestDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestDate
	}
	return nil
}

type MonitoringClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientRequest *Client                `protobuf:"bytes,1,opt,name=client_request,json=clientRequest,proto3" json:"client_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringClientRequest) Reset() {
	*x = MonitoringClientRequest{}
	mi := &file_Monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringClientRequest) ProtoMessage() {}

func (x *MonitoringClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringClientRequest.ProtoReflect.Descriptor instead.
func (*MonitoringClientRequest) Descriptor() ([]byte, []int) {
	return file_Monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *MonitoringClientRequest) GetClientRequest() *Client {
	if x != nil {
		return x.ClientRequest
	}
	return nil
}

type MonitoringServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringServerResponse) Reset() {
	*x = MonitoringServerResponse{}
	mi := &file_Monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringServerResponse) ProtoMessage() {}

func (x *MonitoringServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringServerResponse.ProtoReflect.Descriptor instead.
func (*MonitoringServerResponse) Descriptor() ([]byte, []int) {
	return file_Monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *MonitoringServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_Monitoring_proto protoreflect.FileDescriptor

const file_Monitoring_proto_rawDesc = "" +
	"\n" +
	"\x10Monitoring.proto\x12\n" +
	"Monitoring\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\x06Client\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12=\n" +
	"\frequest_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestDate\"T\n" +
	"\x17MonitoringClientRequest\x129\n" +
	"\x0eclient_request\x18\x01 \x01(\v2\x12.Monitoring.ClientR\rclientRequest\"4\n" +
	"\x18MonitoringServerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2l\n" +
	"\x11MonitoringService\x12W\n" +
	"\n" +
	"Monitoring\x12#.Monitoring.MonitoringClientRequest\x1a$.Monitoring.MonitoringServerResponseB,Z*server/internal/pb/monitoring;monitoringpbb\x06proto3"

var (
	file_Monitoring_proto_rawDescOnce sync.Once
	file_Monitoring_proto_rawDescData []byte
)

func file_Monitoring_proto_rawDescGZIP() []byte {
	file_Monitoring_proto_rawDescOnce.Do(func() {
		file_Monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Monitoring_proto_rawDesc), len(file_Monitoring_proto_rawDesc)))
	})
	return file_Monitoring_proto_rawDescData
}

var file_Monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Monitoring_proto_goTypes = []any{
	(*Client)(nil),                   // 0: Monitoring.Client
	(*MonitoringClientRequest)(nil),  // 1: Monitoring.MonitoringClientRequest
	(*MonitoringServerResponse)(nil), // 2: Monitoring.MonitoringServerResponse
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
}
var file_Monitoring_proto_depIdxs = []int32{
	3, // 0: Monitoring.Client.request_date:type_name -> google.protobuf.Timestamp
	0, // 1: Monitoring.MonitoringClientRequest.client_request:type_name -> Monitoring.Client
	1, // 2: Monitoring.MonitoringService.Monitoring:input_type -> Monitoring.MonitoringClientRequest
	2, // 3: Monitoring.MonitoringService.Monitoring:output_type -> Monitoring.MonitoringServerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Monitoring_proto_init() }
func file_Monitoring_proto_init() {
	if File_Monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Monitoring_proto_rawDesc), len(file_Monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Monitoring_proto_goTypes,
		DependencyIndexes: file_Monitoring_proto_depIdxs,
		MessageInfos:      file_Monitoring_proto_msgTypes,
	}.Build()
	File_Monitoring_proto = out.File
	file_Monitoring_proto_goTypes = nil
	file_Monitoring_proto_depIdxs = nil
}
